spring:
  application:
    name: doctor-study
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ENC(vRvWrSNak8qL4hz99F9Rdpinr2Ge9/yAWeOBKJF0T+3ubtJn82NHt0IqVWBuFic7RVlZM8IN7dnzFEn0ZpHuv/rbhvhqCuCD)
    username: ENC(6J5KDQ0bQcrkcQi8mDQmfQ==)
    password: ENC(jREwrJfAT6XiqxBSlHD8AQ==)
  jpa:
    database: mysql
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true
    defer-datasource-initialization: true
  mail:
    host: smtp.naver.com
    port: 465
    username: ENC(Ie15jnhRnq/z2N/EJokdXoM++8/9lwRplpSZ7088HE8=)
    password: ENC(ylXxe1vHQHzl7Ngc2HDt1xVxShphiJ3P)
    protocol: smtps

  data:
    redis:
      host: redis
      port: 6379
  sql:
    init:
      mode: always

jwt:
  secret: ENC(6Vd+EXILVTQ5Vf2KNjK8DFf9xMn8jYriq0WgklK++xV7EETrbeQculP5bryRYXUyTd5sCOjhcvzmF/l1bGvoQK8Zck5O6jZwjCl7RrtG/9MKmVjWqjKb4GftItjW6g/u6l/PqwSf7YA=)


springdoc:
  swagger-ui:
    path: /swagger-ui.html
    operations-sorter: method
  api-docs:
    path: /api-docs
  default-consumes-media-type: application/json
  default-produces-media-type: application/json

audio-utils:
  upper-path: "audio/"


cloud:
  aws:
    s3:
      bucket: ENC(vWy85kbDoTrKZ4d+sJcKeQ==)
    credentials:
      accessKey1: ENC(RccwEmE0OBKReyZZgYuaUhwP9WthHzH6ymUcAL3CL3I=)
      secretKey1: ENC(/fyQt2sh7eLtVkXe63A7N/FtRIYu8FdeMbGoygQ+DaeGpxIRhR1kU3c6aeVnaBh4KgM5+IWTRzg=)
    region:
      static: ENC(AtRBVGQdxXx9+67aQZ9Wthkvos0j+Lar)
      auto: false
    stack:
      auto: false
---
## local
spring:
  config:
    activate:
      on-profile: local
    import: application-secret.yml

  data:
    redis:
      host: localhost
      port: 6379

